最終課題のユーザー登録機能の実装
shizuka12/final-tasks pull request #1
Opened 2021-04-20 05:08 UTC by shizuka12

ユーザー登録機能を実装しました。ご確認とレビューのほどよろしくお願いいたします。

2021-04-20 09:49 UTC, Shunsuke-Shimura commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
UserCreationFormはデフォルトでUserクラスをモデルとして用いていて、上の3つのフィールドを持っているため、Metaクラスを追加しなくても大丈夫です。

2021-04-20 12:04 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-04-20 12:04 UTC, Akinori13 commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
いくつかのファイルの末尾に、停止マークで、`No newline at end of file`が表示されていると思いますので、改行を入れておいてください。
(参考記事)[https://msfukui.hatenablog.com/entry/2018/12/18/071145]

2021-04-20 12:04 UTC, Akinori13 commented on mysite/accounts/templates/accounts/signup.html
> +<input type="submit" value="login" />
`login`よりも`submit`や`register`などを用いてください。

2021-04-24 00:17 UTC, shizuka12 commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
Metaクラスをなくしたところ、記述することがなくなったので、forms.pyの記述はすべて消して、views.pyに直接UserCreationFormをインポートしました。ご確認ください。

2021-04-24 00:31 UTC, shizuka12 commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
すいません、リンクの記事も読んでみたのですが、停止マークで、No newline at end of fileが表示されるというのがよく分からず、確認できませんでした。
それと、forms.pyの内容をすべて消して、views.pyにUserCreationFormを直接インポートしたのですが、この場合改行するというのはどのようにすればいいでしょうか？

2021-04-24 00:31 UTC, shizuka12 commented on mysite/accounts/templates/accounts/signup.html
> +<input type="submit" value="login" />
loginをsubmitに変更しました。ご確認ください。

2021-04-24 00:44 UTC, Akinori13 commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
画像があるサイトをシェアするべきでした。
[こちら](https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html#toc5)をご参照ください。

2021-04-24 00:47 UTC, Shunsuke-Shimura commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
確認しました。いいと思います。

2021-04-24 00:51 UTC, Shunsuke-Shimura commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
追加ですが、停止マークというのはこのプルリクエストの上の方にある`Files changed`というタブから見れますよ。

2021-04-24 05:31 UTC, shizuka12 commented on mysite/accounts/forms.py
> +        fields = ('username', 'password1', 'password2')
`No newline at end of file`を確認することができました。文末に改行を入れたので、ご確認ください。

2021-04-24 05:39 UTC, Akinori13 approved these changes

2021-04-24 06:50 UTC, Akinori13 commented
テストを書きましょう。

2021-04-26 00:44 UTC, shizuka12 commented
> テストを書きましょう。

テストを書きましたので、ご確認お願いします。

2021-04-26 01:00 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +
プロジェクト内でインデントの大きさは統一しましょう。

2021-04-26 04:06 UTC, shizuka12 commented on mysite/accounts/tests.py
> +
インデントを半角スペース4つに統一しました。

2021-04-26 04:25 UTC, Shunsuke-Shimura commented on mysite/accounts/templates/accounts/signup.html
> +     {% endfor %}
細かいようですが、35行目に余分なスペースが一つあります。

2021-04-26 04:28 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +
いいと思います。

2021-04-26 04:29 UTC, shizuka12 commented on mysite/accounts/templates/accounts/signup.html
> +     {% endfor %}
35行目の余分なスペースを削除しました。

2021-04-26 04:31 UTC, Shunsuke-Shimura commented on mysite/accounts/templates/accounts/signup.html
> +     {% endfor %}
確認しました。

2021-04-26 08:18 UTC, Akinori13 requested changes
ユーザーが保存されているかのテストも実行して下さい。

2021-04-26 08:58 UTC, shizuka12 commented
> ユーザーが保存されているかのテストも実行して下さい。

test_save_of_userを作成したのですが、テストに失敗してしまいます。どこが間違っているのか分からないので、教えていただけないでしょうか？

2021-04-26 09:52 UTC, Shunsuke-Shimura commented
> > ユーザーが保存されているかのテストも実行して下さい。
> 
> test_save_of_userを作成したのですが、テストに失敗してしまいます。どこが間違っているのか分からないので、教えていただけないでしょうか？

パスワードが短すぎるようです。
参考までに特定方法を説明すると、Djangoのソースコードを確認して処理をたどってみたら、どうやら`BaseModelForm`の`save`メソッドに処理がわたっていて、テストを実行したときのエラーメッセージから`ValidationError`が発生していたようなので、`form.error`プロパティをテストコードの方でprintデバッグしてみると、
`<ul class="errorlist"><li>password2<ul class="errorlist"><li>このパスワードは短すぎます。最低 8 文字以上必要です。</li></ul></li></ul>`
のような文字列が表示されます。

2021-04-26 11:17 UTC, shizuka12 commented
> パスワードが短すぎるようです。
> 参考までに特定方法を説明すると、Djangoのソースコードを確認して処理をたどってみたら、どうやら`BaseModelForm`の`save`メソッドに処理がわたっていて、テストを実行したときのエラーメッセージから`ValidationError`が発生していたようなので、`form.error`プロパティをテストコードの方でprintデバッグしてみると、
> `<ul class="errorlist"><li>password2<ul class="errorlist"><li>このパスワードは短すぎます。最低 8 文字以上必要です。</li></ul></li></ul>`
> のような文字列が表示されます。

　すいません、`form.error`プロパティをテストコードの方でprintデバッグしてエラーの特定をするやり方がよく分かりません。具体的にどのようなコードを書けばいいのか教えていただけないでしょうか？
　また、ここでテストが失敗してしまう理由がパスワードが短いことが原因だとしたら、上にある`test_newusername_and_correct_password`
もパスワードが短いはずなのに、なぜテストが成功してしまったのでしょうか？パスワードが短いと`form.is_valid`はFalseになってしまうのではないのですか？

2021-04-26 12:01 UTC, Shunsuke-Shimura commented
> 　すいません、`form.error`プロパティをテストコードの方でprintデバッグしてエラーの特定をするやり方がよく分かりません。具体的にどのようなコードを書けばいいのか教えていただけないでしょうか？
> 　また、ここでテストが失敗してしまう理由がパスワードが短いことが原因だとしたら、上にある`test_newusername_and_correct_password`
> もパスワードが短いはずなのに、なぜテストが成功してしまったのでしょうか？パスワードが短いと`form.is_valid`はFalseになってしまうのではないのですか？

今確認してみると、`test_newusername_and_correct_password`ではメソッド呼び出しの`()`をつけ忘れていますね。そのためTrueになっています。修正おねがいします。
なぜTrueと判断されたかについては、
[https://docs.python.org/ja/3/reference/expressions.html#boolean-operations](url)
のブール演算の項が理由だと思います。
またprintデバッグのやり方は、単純に`test_save_of_user`関数の`form.save()`の前に`print(form.errors)`を加えてテストを実行するだけです。テスト結果の表示の途中で見栄えは悪いですが、先のような出力が出てきます。

2021-04-26 12:09 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        self.assertTrue(form.is_valid)
`form.isvalid`に()をつけ忘れています。

2021-04-26 12:19 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        self.assertTrue(form.is_valid)
`form.isvalid`の()の付け忘れを修正して、長いパスワードで正しくテストすることを確認しました。
また、デバッグもできました。ありがとうございます。

さらに修正、追加を加えました。
(`test_with_short_password`の追加、パスワードを`test_with_short_password`以外は長いものに変更)
確認をお願いします。

2021-04-26 12:27 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
>          form = UserCreationForm({'username': username2, 'password1': 'pass_b', 'password2': 'pass_c'})
passwordが短いもののテストならpassword1とpassword2は一致させましょう。

2021-04-26 12:28 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        self.assertTrue(form.is_valid)
確認しました。

2021-04-26 12:32 UTC, shizuka12 commented on mysite/accounts/tests.py
>          form = UserCreationForm({'username': username2, 'password1': 'pass_b', 'password2': 'pass_c'})
すいません、単純にケアレスミスでした。修正したので、確認お願いします。

2021-04-26 12:33 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
>          form = UserCreationForm({'username': username2, 'password1': 'pass_b', 'password2': 'pass_c'})
確認しました。

2021-04-26 13:17 UTC, Akinori13 approved these changes

2021-04-26 13:20 UTC, merged