最終課題：お気に入り機能の実装
shizuka12/final-tasks pull request #10
Opened 2021-06-06 14:41 UTC by shizuka12

お気に入り機能の実装をしました。

・tmeet_detailページにアクセスすると、お気に入りボタン(既にお気に入りに登録していた場合はお気に入り解除ボタン)が表示され、クリックするとお気に入り(もしくはお気に入り解除)に登録できるようにしました。
・tmeet_detailページにお気に入り数を非同期で表示させ(お気に入り数が0の場合は表示されません)、クリックするとそのツミートをお気に入りにしたアカウントが表示されるようにしました。
・アカウントページのお気に入りツミート数をクリックすると、そのアカウントがお気に入りにしたツミートが表示されるようにしました。

2021-06-06 15:21 UTC, Shunsuke-Shimura commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +{% block javascript %}
`base.html`でのこのブロックの展開先がないように見えます。問題なく表示されてはいますが、一応base.htmlに追加しておきましょう。

2021-06-06 15:22 UTC, Shunsuke-Shimura commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +{% load static %}
`static`ファイルとしてjavascriptやimgファイルなどを使っていないのであれば`load static`は必要ありません。

2021-06-06 15:24 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +        self.client.post(reverse('tmitter:favorite'), data={'pk': self.tmeet.pk})
同じ文が重複してしまっています。

2021-06-06 15:35 UTC, Shunsuke-Shimura commented on mysite/tmitter/views.py
> +    import json
いらなそうなので消しましょう。

2021-06-06 15:37 UTC, Shunsuke-Shimura commented on mysite/tmitter/views.py
> +        get_object_or_404(Favorite,fav_from=fav_from, tmeet=tmeet).delete()
上で取得済みなので、`get_object_or_404`ではなく`favorite`で大丈夫です。

2021-06-06 15:43 UTC, Shunsuke-Shimura commented on mysite/tmitter/views.py
> +        'user': user,
`user`はデフォルトであるのでいらないです。

2021-06-06 15:53 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        self.client.post(reverse('tmitter:favorite'), data={'pk': self.tmeet.pk})
お気に入りの登録も解除も同じURLで設定しているので、最初の`post`でまずお気に入りに登録して、次の`post`でお気に入り解除をしています。

2021-06-06 16:02 UTC, shizuka12 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +{% block javascript %}
こういうことで大丈夫でしょうか？
https://github.com/shizuka12/final-tasks/blob/9a08d595cfecbd85de307ca5f6065aa588476181/mysite/templates/base.html#L8-L12

2021-06-06 16:03 UTC, shizuka12 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +{% load static %}
消しました。

2021-06-06 16:04 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    import json
消しました。

2021-06-06 16:05 UTC, shizuka12 commented on mysite/tmitter/views.py
> +        get_object_or_404(Favorite,fav_from=fav_from, tmeet=tmeet).delete()
80行目の`get_object_or_404(Favorite,fav_from=fav_from, tmeet=tmeet)`を`favorite`に変更しました。

2021-06-06 16:05 UTC, shizuka12 commented on mysite/tmitter/views.py
> +        'user': user,
消しました。

2021-06-07 00:03 UTC, Shunsuke-Shimura commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +{% block javascript %}
テンプレートブロックで入れ子構造はサポートされているのかわからないですね。
二つに分けるか内側のブロック自体を取り除いた方がいいかもしれないですね。

2021-06-07 00:05 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +        self.client.post(reverse('tmitter:favorite'), data={'pk': self.tmeet.pk})
それでしたらここではお気に入りの解除のテストが目的なので、登録は直接データベースにした方がテストの独立性の観点から良いと思います。

2021-06-07 01:50 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        self.client.post(reverse('tmitter:favorite'), data={'pk': self.tmeet.pk})
最初の登録のところを`Favorite.objects.create(fav_from=self.user1, tmeet=self.tmeet)`に変更しました。

2021-06-07 02:13 UTC, shizuka12 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +{% block javascript %}
`base.html`の`{% block javascript %}`を`{% block content %}`の外に出し、`tmeet_detail.html`の`{% block javascript %}`も外に出しました。

2021-06-08 05:07 UTC, fumiharun11 requested changes
全体の構成について基本的に問題は無いと思います。
何点か質問やお願いをしているので、コメント及び修正をお願いします。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +                'fav_num': "<p><a href='" + str(reverse('tmitter:tmeet_fav_detail', kwargs={'pk': pk})) + "'</a>" + str(fav_num) + " お気に入り</p>",
バックエンド側の責務を考えると値にマークアップを含めているのは適していないように感じました。
pタグの生成はフロントエンド側で行うようにしましょう。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +                'fav_num': "<p><a href='" + str(reverse('tmitter:tmeet_fav_detail', kwargs={'pk': pk})) + "'</a>" + str(fav_num) + " お気に入り</p>",
同上

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +    else:
同じような処理で`return`されている箇所が多いですが、全て`JsonResponse`を返しているので`return`文を一つのみにして書ければ書いてみてください。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/models.py
> +    fav_from = models.ForeignKey(User, related_name='fav_from', on_delete=models.CASCADE)
`fav_from`が`User`を指すと判断しにくいので`fav_user`や`from_user`などでも良さそうですね。
`related_name`がフィールド名と同様だと逆参照の際に違和感があると思うのですが、その点については如何ですか？

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/models.py
> +    tmeet = models.ForeignKey(Tmeet, related_name='tmeet', on_delete=models.CASCADE)
同上
> `related_name`がフィールド名と同様だと逆参照の際に違和感があると思うのですが、その点については如何ですか？

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/models.py
> +    fav_date = models.DateTimeField(auto_now_add=True)
`fav_date`というフィールド名が`DateField`で定義されたフィールドとも読み取れるので`created_at`なども今後の命名の候補に入れてみてください。
今回は必須の修正とはしません。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/models.py
> +        return self.fav_from.username + " favorited " + self.tmeet.content
`__str__`メソッドを呼び出す側の処理によってはSQLが大量に発行される可能性があるように見えるので、呼び出す側で`select_related`などを用いるように注意してください。

参考: https://docs.djangoproject.com/en/3.2/ref/models/querysets/#select-related

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +{% if is_favoriting %}
短く簡潔に書きたい場合は以下のような書き方も出来るので、参考にどうぞ。
```html
<button id="favorite" value="{{ pk }}">お気に入り{% if is_favoriting %}解除{% endif %}</button>
<p id="embed">{% if fav_num != 0 %}<a href="{% url 'tmitter:tmeet_fav_detail' tmeet.pk %}">{{ fav_num }} お気に入り</a>{% endif %}</p>
```

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +        var cookieValue = null;
個人的に`let`や`const`を用いても良い印象を受けたので、(ここ以降含めて)宣言に`var`を用いている意図はありますか？

参考: https://docs.djangoproject.com/en/3.2/ref/csrf/

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +                console.log(csrftoken);
不要なconsoleかと思うので削除をお願いします。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +                success:function(data){
修正必須ではありませんが、`Deferred`というものを用いた記述方法があります。余裕があれば調べてみてください。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/urls.py
> +    path('tmeet_fav_detail/<int:pk>/', tmeet_fav_detail, name='tmeet_fav_detail'),
他のURL構造がここと同様のルールを採用しているので修正必須というわけではないですが、個人的に区切り文字は`-`をお勧めします。

参考: https://developers.google.com/search/docs/advanced/guidelines/url-structure

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +from django.http import JsonResponse
この段階だと修正必須ではないですが、importルールについて改めて確認をお願いします。
参考: https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#imports

VSCodeをお使いであれば、ある程度は自動でソートしてくれる機能もあるので調べてみてください。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +        # 'user': user,
不要であれば消した方が良いと思います。残している意図があればコメントを追加してください。

2021-06-08 05:07 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +        'pk': pk,
tmeetのpkを単体でcontextに含めている理由を教えてください。

2021-06-08 09:56 UTC, shizuka12 commented on mysite/tmitter/models.py
> +    fav_from = models.ForeignKey(User, related_name='fav_from', on_delete=models.CASCADE)
`fav_from`は`fav_user`に変更しました。

`related_name`に関しては、恥ずかしながらそもそも逆参照や`related_name`についてよく理解しないまま書いていたので、フィールド名と同じものにしてしまっていました。
今回、`related_name`を`fav_from`から`faved_tmeet`に変更しました。

2021-06-08 09:57 UTC, shizuka12 commented on mysite/tmitter/models.py
> +    tmeet = models.ForeignKey(Tmeet, related_name='tmeet', on_delete=models.CASCADE)
`tmeet`の`related_name`は`faved_user`に変更しました。

2021-06-08 09:58 UTC, shizuka12 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +        var cookieValue = null;
varを用いている意図は特になかったので、letやconstに書き換えました。

2021-06-08 09:58 UTC, shizuka12 commented on mysite/tmitter/templates/tmitter/tmeet_detail.html
> +                console.log(csrftoken);
削除しました。

2021-06-08 10:01 UTC, shizuka12 commented on mysite/tmitter/views.py
> +        # 'user': user,
不要でしたので、消しました。

2021-06-08 10:02 UTC, shizuka12 commented on mysite/tmitter/views.py
> +        'pk': pk,
見返してみたら、ここのpkは必要なかったので、消しました。それに伴って、`tmeet_detail.html`で`{{ pk }}`としていたところは、`{{ tmeet.pk }}`に変更しました。

2021-06-08 10:18 UTC, shizuka12 commented on mysite/tmitter/views.py
> +                'fav_num': "<p><a href='" + str(reverse('tmitter:tmeet_fav_detail', kwargs={'pk': pk})) + "'</a>" + str(fav_num) + " お気に入り</p>",
ビューはこのように変更し、
https://github.com/shizuka12/final-tasks/blob/f3a2dc806eec146b792592a9f4e7a6d630bfdd5c/mysite/tmitter/views.py#L83-L86
フロントエンド側では、
pタグではなく、aタグにidを埋め込み、
https://github.com/shizuka12/final-tasks/blob/128d4cc42d8f4e296d797b3f546612856fb67e71/mysite/tmitter/templates/tmitter/tmeet_detail.html#L20
Ajaxの処理の部分では`('#embed').html`としていたのを`('#embed').text`に変更しました。
https://github.com/shizuka12/final-tasks/blob/128d4cc42d8f4e296d797b3f546612856fb67e71/mysite/tmitter/templates/tmitter/tmeet_detail.html#L85

2021-06-08 10:18 UTC, shizuka12 commented on mysite/tmitter/views.py
> +                'fav_num': "<p><a href='" + str(reverse('tmitter:tmeet_fav_detail', kwargs={'pk': pk})) + "'</a>" + str(fav_num) + " お気に入り</p>",
こちらも上と同じように修正しました。

2021-06-08 10:24 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    else:
https://github.com/shizuka12/final-tasks/blob/f3a2dc806eec146b792592a9f4e7a6d630bfdd5c/mysite/tmitter/views.py#L89-L101
このように、それぞれの`JsonResponse`を`response`に代入し、最後に`return response`としたのですが、これで大丈夫でしょうか？

2021-06-08 10:36 UTC, shizuka12 commented on mysite/tmitter/models.py
> +        return self.fav_from.username + " favorited " + self.tmeet.content
https://github.com/shizuka12/final-tasks/blob/f3a2dc806eec146b792592a9f4e7a6d630bfdd5c/mysite/tmitter/views.py#L105-L109
この部分のビューをselect_relatedを用いたものに変更しました。

2021-06-09 10:37 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +        'pk': pk,
Good

2021-06-09 10:58 UTC, fumiharun11 commented on mysite/tmitter/models.py
> +    fav_from = models.ForeignKey(User, related_name='fav_from', on_delete=models.CASCADE)
### 提案
`User`のインスタンスから`Favorite`を逆参照するときに`user.faved_tmeet.all()`のようなコードが書かれることを想像したのですが、これは`Tmeet`の一覧を取得するようにも見えます。
`related_name='favorites'`など`Favorite`の一覧を取得していることを示せるような`related_name`が良いと考えているのですが、意見があれば伺いたいです。

2021-06-09 11:02 UTC, fumiharun11 commented on mysite/tmitter/models.py
> +    tmeet = models.ForeignKey(Tmeet, related_name='tmeet', on_delete=models.CASCADE)
同上

> ### 提案
> `User`のインスタンスから`Favorite`を逆参照するときに`user.faved_tmeet.all()`のようなコードが書かれることを想像したのですが、これは`Tmeet`の一覧を取得するようにも見えます。
> `related_name='favorites'`など`Favorite`の一覧を取得していることを示せるような`related_name`が良いと考えているのですが、意見があれば伺いたいです。

2021-06-09 11:03 UTC, fumiharun11 commented on mysite/tmitter/models.py
> +        return self.fav_from.username + " favorited " + self.tmeet.content
`tmeet`に対しては`select_related`を適用しませんか？

2021-06-09 11:16 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +    else:
実装上問題はないと思いますが、`dict`型の変数dataをif分岐処理の前に定義しておき、if文処理の中でkey&valueを更新するという方法もあります。その際、`return`文が次のように書けると思います。
```py
return JsonResponse(data)
```

2021-06-10 10:55 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    else:
以下のように変更しました。
https://github.com/shizuka12/final-tasks/blob/dbfc56d84d7652a9f9fe7724b4ad6c2a623bc4b7/mysite/tmitter/views.py#L89-L101

2021-06-10 10:57 UTC, shizuka12 commented on mysite/tmitter/models.py
> +    fav_from = models.ForeignKey(User, related_name='fav_from', on_delete=models.CASCADE)
確かにそうですね。
`fav_user`の`related_name`を`favorite`に変更しました。

2021-06-10 11:01 UTC, shizuka12 commented on mysite/tmitter/models.py
> +    tmeet = models.ForeignKey(Tmeet, related_name='tmeet', on_delete=models.CASCADE)
`tmeet`の`related_name`も`favorites`に変更しました。

2021-06-10 11:13 UTC, shizuka12 commented on mysite/tmitter/models.py
> +        return self.fav_from.username + " favorited " + self.tmeet.content
`tmeet`と`follow`にも適用させ、以下の4か所に新たに`select_related`を追加しました。

・18行目の`tmeet_list`
https://github.com/shizuka12/final-tasks/blob/4c5704ae12dc212aa3314c9d050db7f3111dba50/mysite/tmitter/views.py#L14-L20
・120行目の`fav_list`
https://github.com/shizuka12/final-tasks/blob/4c5704ae12dc212aa3314c9d050db7f3111dba50/mysite/tmitter/views.py#L114-L127
・84行目の`following_list`
https://github.com/shizuka12/final-tasks/blob/4c5704ae12dc212aa3314c9d050db7f3111dba50/mysite/accounts/views.py#L80-L86
・94行目の`follower_list`
https://github.com/shizuka12/final-tasks/blob/4c5704ae12dc212aa3314c9d050db7f3111dba50/mysite/accounts/views.py#L90-L96

2021-06-10 11:27 UTC, shizuka12 commented
https://github.com/shizuka12/final-tasks/blob/4c5704ae12dc212aa3314c9d050db7f3111dba50/mysite/tmitter/views.py#L114-L119
一次レビューの際に、この119行目の`user`がデフォルトであるのでいらない、とのレビューを受けたので、消していました。
しかし、先ほど気づいたのですが、ここに`user`を書いておかないと、テンプレートで`{{ user.username }}`としているところが、ブラウザ上では`user.usernmae`ではなく、`request.username`で表示されてしまいます。
ここの`user`はやはり書いておく必要があるのでしょうか？

2021-06-11 07:00 UTC, fumiharun11 reviewed
> 一次レビューの際に、この119行目の`user`がデフォルトであるのでいらない、とのレビューを受けたので、消していました。
> しかし、先ほど気づいたのですが、ここに`user`を書いておかないと、テンプレートで`{{ user.username }}`としているところが、ブラウザ上では`user.usernmae`ではなく、`request.username`で表示されてしまいます。
> ここの`user`はやはり書いておく必要があるのでしょうか？

この件について該当箇所にコメントしました。
また、他の箇所にもコメントを追加したので確認お願いします。

2021-06-11 07:00 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +        'user': user,
template内にデフォルトで渡されている`user`について、ログイン時は`auth.User`、未ログイン時は`AnonymousUser`のインスタンスが渡されます。
[ここ](https://github.com/shizuka12/final-tasks/pull/10/files#diff-4f5998ac8fbc0a7662499ac4e6e0a1bde5c35f5a15114b6d3a323ec6cf2ecfbbR115)ではpathに含まれる`user_id`に該当する`User`のインスタンスを取得しているので不要ではないですね。このまま残しておきましょう。
ただし、以下のように記述するとデフォルトで渡されている`user`を上書きした形でtemplateに渡されるので注意してください。（絶対ダメな訳ではないので修正必須ではないです）
```py
'user': user
```

参考: https://docs.djangoproject.com/en/3.2/ref/templates/api/#django-contrib-auth-context-processors-auth

2021-06-11 07:00 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +def favorite(request):
こちら見逃していたのですが、`POST`メソッドでリクエストする想定のみのViewであれば`require_POST`をデコレータするのはどうでしょうか？

2021-06-11 07:00 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +    if not (created):
参考: ここからの処理は以下のように記述することも可能です。修正するかどうかはお任せします。
```py
if not created:
    favorite.delete()
fav_num = Favorite.objects.filter(tmeet=tmeet).count()
data = {
    'fav_num': f'{fav_num} お気に入り' if fav_num != 0 else '',
    'button': 'お気に入り解除' if created and fav_num != 0 else 'お気に入り'
}
```

2021-06-11 07:00 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +                'fav_num': "",
`num`という命名をしているのでこの場合は空文字列ではなく`'0'`を渡した方が良いと考えていますがどうでしょう？
実際に、[比較する時](https://github.com/shizuka12/final-tasks/pull/10/files#diff-b49258d0a0e6bdee2e7049221c9e89d0e38cf03e5c1d91c0bb5e99aeda1e0e83R20)にも0かどうかの判定をしているのでここは気になりました。

2021-06-11 08:04 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    if not (created):
もしこのように記述する場合、`button`のところの`and fav_num != 0`は不要なようにも感じられたのですが、これは必要でしょうか？

2021-06-11 08:05 UTC, shizuka12 commented on mysite/tmitter/views.py
> +                'fav_num': "",
Twitterでは、お気に入り数が０の時にお気に入り数自体表示されない仕様になっており、それに合わせようと思っているので、空文字列を渡しています。

もしここで空文字列ではなく０を渡していた場合、
自分だけがお気に入りにしているツミートにアクセスすると、
→「１お気に入り」と表示される
→この状態でお気に入り解除
→「０」と表示される
という状態になってしまうことが考えられたので、空文字列を渡しました。

2021-06-11 08:11 UTC, shizuka12 commented on mysite/tmitter/views.py
> +def favorite(request):
つまり、`@login_required`の記述を消して、代わりに`@require_POST`を記述するということでいいでしょうか？

2021-06-11 08:33 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +                'fav_num': "",
理解しました。こちらについてはokです。

2021-06-11 08:33 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +    if not (created):
その方針にした場合、`if created`を満たしていたら`"お気に入り解除"`になりますが、`fav_num == 0`の時は[ここ](https://github.com/shizuka12/final-tasks/pull/10/files#diff-4f5998ac8fbc0a7662499ac4e6e0a1bde5c35f5a15114b6d3a323ec6cf2ecfbbR94)を見て分かるように`"お気に入り"`になっています。この点については如何ですか？

2021-06-11 08:33 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +def favorite(request):
既に実装済のViewと同様に複数デコレータを掛けるのはどうでしょうか？
https://github.com/shizuka12/final-tasks/blob/9da1a7338ab4479865e7ca3f1687c6b707bd9444/mysite/tmitter/views.py#L52-L54

2021-06-11 08:53 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    if not (created):
そもそも[ここ](https://github.com/shizuka12/final-tasks/pull/10/files#diff-4f5998ac8fbc0a7662499ac4e6e0a1bde5c35f5a15114b6d3a323ec6cf2ecfbbR94)で`"お気に入り"`としていたこと自体が間違っていました。正しくは`"お気に入り解除"`です。

2021-06-11 09:28 UTC, shizuka12 commented on mysite/tmitter/views.py
> +def favorite(request):
複数デコレーターを掛けました。
https://github.com/shizuka12/final-tasks/blob/f9fc68bde5efb3dbd63f56b0ef9efe748fd6b3b8/mysite/tmitter/views.py#L70-L72

2021-06-14 03:30 UTC, fumiharun11 commented on mysite/tmitter/views.py
> +    if not (created):
確かにそうですね。
それであれば`created`について判定すれば良さそうなので、`fav_num`については含めなくて大丈夫そうです。
こちら対応お願いします。

2021-06-14 03:50 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    if not (created):
以下のように`button`の`and fav_num != 0`の記述を削除しました。
https://github.com/shizuka12/final-tasks/blob/4d5bf1d9679ffbab6307f238f0dcaf5fcb700eb7/mysite/tmitter/views.py#L82

2021-06-14 04:05 UTC, fumiharun11 approved these changes
LGTM

2021-06-14 04:11 UTC, merged