最終課題：ツイート機能の実装
shizuka12/final-tasks pull request #6
Opened 2021-05-11 13:40 UTC by shizuka12

追加点
・ツイート機能を実装し、トップページにはすべてのアカウントのツイートが、アカウントページにはそのアカウントのツイートが表示されるようにしました。
・ツイートをクリックすると詳細ページに移動し、ツイートをしたユーザー本人であれば詳細ページに削除ボタンが表示され、ツイート削除ができるようにしました。

変更点
・accountsディレクトリのforms.pyは不要だったので削除しました。
・accountsアプリで管理していたトップページを、tmitterアプリでの管理に変更しました。

2021-05-11 15:12 UTC, Shunsuke-Shimura commented on mysite/tmitter/urls.py
> +    path('delete_tmeet/<int:user_id>/<int:pk>/', delete_tmeet, name='delete_tmeet'),
Viewを見ると`accountpage`以外では`user_id`が必要ないように思います。
URLに`user_id`を持たせた意図は何でしょう？
基本的に`login_required`を使っているのであればログインしていることは保証されるので、`request.user`でログインユーザにはアクセスできるため、そちらを使いましょう。
必要なければ`user_id`は消去し、`reverse()`や`url`テンプレートタグ、ビューの関数を修正してください。

2021-05-11 23:12 UTC, shizuka12 commented on mysite/tmitter/urls.py
> +    path('delete_tmeet/<int:user_id>/<int:pk>/', delete_tmeet, name='delete_tmeet'),
`accountpage`以外のuser_idを消去し、`reverse()`なども修正しました。

2021-05-12 01:18 UTC, shunsuke44 commented on mysite/accounts/tests.py
> +from django.contrib.auth import login, logout
このモジュールのlogin, logoutは使っていないようなので消しておきましょう

2021-05-12 01:19 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +        self.client = Client()
`client`はもともと定義されているのでいりません

2021-05-12 01:21 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +from django.contrib.auth import login
`login`は使っていないので消しておきましょう。

2021-05-12 01:28 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +            self.assertEqual(queryset[i].content, self.accountpage_list[i])
このテストはアカウントページの実装に依存してしまっているため、アカウントページの実装を変更したいと思ったときにこのテストも変更しなくてはならないようになっています。
ですので、テストはなるべくほかの実装と切り離した方がよいでしょう。
（例としては単にデータベースに存在することを確かめるようにするなど）

2021-05-14 13:45 UTC, shizuka12 commented on mysite/accounts/tests.py
> +from django.contrib.auth import login, logout
消しました。

2021-05-14 13:45 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        self.client = Client()
`self.client = Client()`を削除しました。

2021-05-14 13:45 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +from django.contrib.auth import login
消しました。

2021-05-14 13:46 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +            self.assertEqual(queryset[i].content, self.accountpage_list[i])
データベースに存在するかを確かめるだけにしました

2021-05-14 14:14 UTC, Shunsuke-Shimura commented
確認しました。

2021-05-15 08:00 UTC, Akinori13 requested changes
いくつかコメントしました。
・CreateViewTestsの追加をしましょう。
・テストでは、Modelのテストだけでなく、Viewのテストも行いましょう。

2021-05-15 08:00 UTC, Akinori13 commented on mysite/tmitter/views.py
> +    user = request.user
この`user`は必要ありますか。

2021-05-15 08:00 UTC, Akinori13 commented on mysite/tmitter/views.py
> +    return redirect('tmitter:accountpage', request.user.id)
現状では、CさんがBさんのツミートを削除できてしまいます。Bさんだけがツミート削除できるようにしてください。
フロントエンドだけのバリデーションは安全ではありません。
善意のユーザーがアプリを利用するとき、フロントエンドのUIで上記の不正リクエストを防げます。
悪意のユーザーがアプリを利用するとき、開発者ツールなどを用いて不正リクエストが可能です。
【簡単な例】
1. Aさんがツミート(id=1)して、ログアウトします。
2. Bさんでログインして、`tmitter/tmeet_detail/1/`を開きます。
3. ログアウトボタンが含まれているFormタグを開発者ツールで確認します。
4. formのaction属性を`/tmitter/delete_tmeet/1/`に変更します。
5. ログアウトボタンを押して、OKを押します。
6. これで不正リクエストの完了です。

2021-05-15 08:00 UTC, Akinori13 commented on mysite/accounts/tests.py
> +        user_info = User.objects.get(username=username2)
これは何に使いますか。もし不要だったら消しちゃいましょう。

2021-05-15 08:00 UTC, Akinori13 commented on mysite/accounts/tests.py
> +        user_info = User.objects.get(username=username)
これも何に使いますか。もし不要だったら消しちゃいましょう。

2021-05-15 13:37 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    user = request.user
必要ないので削除しました。

2021-05-15 13:39 UTC, shizuka12 commented on mysite/tmitter/views.py
> +    return redirect('tmitter:accountpage', request.user.id)
`mysite/tmitter/views.py`の50行目に`if user == tmeet.author`を追加し、ツミートを作成したユーザーのみがツミートを削除できるようにしました。

2021-05-15 13:40 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        user_info = User.objects.get(username=username2)
不要なので消しました。

2021-05-15 13:40 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        user_info = User.objects.get(username=username)
不要なので消しました。

2021-05-15 13:44 UTC, shizuka12 commented
> ・CreateViewTestsの追加をしましょう。
・テストでは、Modelのテストだけでなく、Viewのテストも行いましょう。

すいません、具体的にどういったテストを追加する必要があるのかが分からないのですが、教えていただけないでしょうか？

2021-05-15 15:16 UTC, Akinori13 commented
> > ・CreateViewTestsの追加をしましょう。
> > ・テストでは、Modelのテストだけでなく、Viewのテストも行いましょう。
> 
> すいません、具体的にどういったテストを追加する必要があるのかが分からないのですが、教えていただけないでしょうか？

一つ目は、ツミートの新規作成時のテストを行ってほしいということです。140字以上で投稿した場合に、エラーになるかなど。

二つ目は、削除後のリダイレクトやHTTPステータスは適切か、本当に削除されているかなどです。（MVTが理解できてなかったら質問してください。）
_____
テストの書き方は正直僕も悩んでいますが、本当に千差万別です。
### 僕が最初に試した方法
ModelのテストとViewのテストに分離してみる
**Modelに対するテスト**
Modelの新規作成、削除、更新のテストをします。Viewに依存せず、Clientなどは使いません。例えば、create_model_testでは、create()してmodel.count()の値が増えているかなど。
**Viewに対するテスト**
ClientでPOSTして、リダイレクトやHTTPステータス、使用されているTemplateが正しいか、querysetの中身は適切かなどのチェックです。例えば、login_view_testでは、ログイン後のトップページに自分の名前があるかのチェックです。

正直、「ModelのテストはViewのテストに含まれているよね？」と思いました。（例：create_model_testはcreate_view_testに含まれてるよね。）

### 僕が今試している方法
これもModelのテストとViewのテストに分離してみる
**Modelに対するテスト**
Modelのメソッドにのみ注目する。例えば、Tweetモデルに内容の最初の20文字のみ表示するメソッドがあれば、これが適切に動くかのテストをする。
**Viewに対するテスト**
これは最初のやつと同じ。

これでテスト駆動開発の中で重複せずにテストできるのかな、と思ってる。
____
正直僕も難しく感じているので、次のもくもく会で質問します。
でも、テスト駆動開発に関わらず、Viewに対するテストはすべきなので、上を参考にやってみてください。

2021-05-17 10:30 UTC, shizuka12 commented
ひとまず、
・ツミートを削除したらアカウントページにリダイレクトされるかどうか(`test_delete_redirect`)
・140文字以上のツミートは作成できないかどうか(`test_with_over_length_tmeet`)
・ツミートしたらアカウントページにリダイレクトされるかどうか(`test_tmeet_redirect`)
のテストを書きました。
<br>
`test_delete_redirect`はうまくいったのですが、`test_with_over_length_tmeet`では、140文字超えのツミートも作成できてしまい、うまくいきませんでした(ちなみに実際にサーバーを起動させてブラウザで動作確認をした時には、ツミートの欄に140文字以上は入力できず、140文字越えのツミートは作成できませんでした)。

また、`test_tmeet_redirect`も`AssertionError: 200 != 302 : Response didn't redirect as expected: Response code was 200 (expected 302)`と表示されてしまい、うまくいきませんでした。
_____
ModelとViewのテストの分離など詳しくお聞きしたいこともあるので、もし明日のもくもく会に参加されるのであればよろしくお願いします。

2021-05-18 02:14 UTC, Akinori13 requested changes
コメントしました。

2021-05-18 02:14 UTC, Akinori13 commented on mysite/tmitter/tests.py
> +            content += sentence
```suggestion
            content += "あいうえおかきくけこ"
```

2021-05-18 02:14 UTC, Akinori13 commented on mysite/tmitter/tests.py
> +        self.client.login(username='username1', password='password_1')
これは`setUp`へ。

2021-05-18 02:14 UTC, Akinori13 commented on mysite/tmitter/tests.py
> +        print(queryset)
必要ないなら消しちゃいましょう。

2021-05-18 02:14 UTC, Akinori13 commented on mysite/tmitter/tests.py
> +    def test_with_over_length_tmeet(self):
`save()`時にバリデーションチェックはなされません。`full_clean()`などでチェックをしましょう。

2021-05-18 02:14 UTC, Akinori13 commented on mysite/tmitter/tests.py
> +        response = self.client.post(reverse('tmitter:tmeet'))
Djangoは、特に指定のない限り、各フィールドに`null=false`をデフォルトにセットしています。post時にcontentが無いので、リダイレクトすることなく、元のページを再度getします。

2021-05-18 10:07 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        self.client.login(username='username1', password='password_1')
`setUp`に入れました

2021-05-18 10:08 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        print(queryset)
消しました。

2021-05-18 10:08 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +    def test_with_over_length_tmeet(self):
`full_clean()`を用いてバリデーションチェックをし、テストが成功したことを確認しました。

2021-05-18 10:09 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        response = self.client.post(reverse('tmitter:tmeet'))
`content`, `author_id`を追加し、テストが成功したことを確認しました。

2021-05-18 10:44 UTC, shizuka12 commented
`test_top_username`と`test_accountpage_username`を追加し、ログイン後のトップページやアカウントページに自分の名前があるかどうかののチェックをしました。

2021-05-18 12:21 UTC, Akinori13 commented on mysite/tmitter/tests.py
> +        response = self.client.post(reverse('tmitter:tmeet'))
`content`の方はOK。
一方で`author_id`の方には二つの解決すべきことがあります。
**①解決すべきこと**
Tmeetモデルにはauthor_idフィールドは存在していません。ここで記載できるとしたらauthorフィールドになります。
もしauthorフィールドを指定したい場合は、`author=1`や`author=user.id`ではなく`author=user`と記述します。

**②解決すべきこと**
views.pyの`tmeet`関数で記述してある通り、tmeet.authorはrequest.userが入るので、普通にPOSTする限りは、このようなPOSTはありえません。
したがって、`'author_id': 1`は消しちゃいましょう。
ついでに悪意あるユーザーが別ユーザーになりすまして投稿することができないこともテストしましょう。

2021-05-18 15:30 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        response = self.client.post(reverse('tmitter:tmeet'))
`'author_id': 1`を消しました。

また、`test_by_another_user`を追加し、別のユーザーがツミートできないことを確認しました。

2021-05-19 00:54 UTC, Akinori13 commented on mysite/tmitter/tests.py
> +        self.client.post(reverse('tmitter:tmeet'), {'content': 'this is test_tmeet_rqedirect'})
なりすましてのツミートなので、
```python
self.client.post(reverse('tmitter:tmeet'), {'content': 'this is test_tmeet_rqedirect', 'author': self.user})
```
のようにします。
このようにすることで、Viewが予想している通りに動作しているかをテストできます。

2021-05-19 01:33 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        self.client.post(reverse('tmitter:tmeet'), {'content': 'this is test_tmeet_rqedirect'})
修正しました。

2021-05-19 04:18 UTC, Akinori13 approved these changes

2021-05-19 04:18 UTC, merged