【修正版】最終課題：フォロー機能の実装
shizuka12/final-tasks pull request #9
Opened 2021-05-30 03:29 UTC by shizuka12

フォロー機能の実装をしました。

**追加点**
・自分以外のアカウントページに、フォローボタン(既にフォローしている場合はフォロー解除ボタン)を配置し、クリックするとフォロー(もしくはフォロー解除)できるようにしました。
・アカウントページのフォロー数、フォロワー数をクリックするとフォロー一覧、フォロワー一覧がそれぞれ表示されるようにしました。

~~**変更点**
・トップページにはすべてのアカウントのツミートではなく、自分と自分がフォローしているアカウントのツミートが表示されるようにしました。~~
→トップページに全員のツミートが表示される仕様に戻しました。
(現在ユーザーIDからのみでしかフォローができず、IDのみでフォロー機能を使うのは厳しいので、トップページで全員分のツイートが見れるようにして、そこから各アカウントページに飛んでフォローをできるようにしました。)

2021-05-30 03:41 UTC, shizuka12 commented
https://github.com/shizuka12/final-tasks/blob/b6fba4a224845e4c1149337093e4257e8f676cb8/mysite/tmitter/views.py#L14-L17
すいません、ここを削除し忘れていたので、削除しました。

2021-05-30 04:37 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +        self.client.login(username='username3', password='password_3')
いらない`login`は消しましょう。

2021-05-30 04:39 UTC, Shunsuke-Shimura commented on mysite/accounts/views.py
> +        following = User.objects.get(pk=user_id)
例外安全性を考えるとここは`get_object_or_404`がいいと思います。

2021-05-30 04:39 UTC, Shunsuke-Shimura commented on mysite/accounts/views.py
> +        following = User.objects.get(pk=user_id)
こちらも`get_object_or_404`がいいでしょう。

2021-05-30 04:40 UTC, Shunsuke-Shimura commented on mysite/accounts/views.py
> +        following = User.objects.get(pk=user_id)
[https://docs.python.org/ja/3/tutorial/errors.html#handling-exceptions](url)
参考URLです。

2021-05-30 04:42 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        request = reverse('accounts:unfollow', args=str(2))
requestオブジェクトと混同しそうなので単純にurlとしてください。

2021-05-30 04:53 UTC, shunsuke44 commented on mysite/accounts/tests.py
> +        self.assertEqual(followings, 3)
`user2`をアンフォローして`user3`のみがデータベースに残っていることを確かめていると思うのですが、もっと直接的にデータベースに存在しているかを確かめる方法があります。
`follow = Follow.objects.filter(follower=self.user2, folloing=self.user2).exists()`
などとするといいでしょう。
あと、オブジェクトをidで直接表現するのはやめましょう。
現在はテストケースごとに新しいデータベースが作成され、idは1から始まるようになっていますが、テスト用データベースを保存しテストの実行速度を向上させる機能もDjangoにはあるため、その場合にテストは失敗してしまいます。

2021-05-30 04:55 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        Follow.objects.get_or_create(follower_id=1, following_id=3)
`get_or_create`はオブジェクトを何としてでも取得したい場合の書き方なので、代入する変数が何もなく、ただ作成したい場合には普通に`create`でいいでしょう。

2021-05-30 04:58 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        Follow.objects.get_or_create(follower_id=3, following_id=1)
ここも`create`でいいと思います。
補足ですが、ビルトインの`Model`の`objects`アトリビュートはデータベースへの処理を行うマネージャを表します。

2021-05-30 05:00 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        follower_id_list = [3, 2]
ここも、idは使わないでください。

2021-05-30 05:06 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        following_id_list = [3, 2]
ここもidは直接使わない方がいいでしょう。

2021-05-30 05:12 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        self.assertEqual(queryset[0].follower.username, "username1")
ここは`queryset`ではなく
`Follow.objects.filter(follower=self.user1, following=self.user2).get()`
でFollowインスタンスを取得してしまうのがいいでしょう。
また、比較もインスタンス同士の比較でいいと思います。（参考）
[https://docs.djangoproject.com/en/3.2/ref/models/instances/#eq](url)

2021-05-30 05:23 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        request = reverse('accounts:follow', args=str(1))
ここも変数名urlにしておきましょう。

2021-05-30 05:25 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        self.assertEqual(queryset.first(), None)
ここも、`filter().exists()`を用いてわかりやすい記述にしましょう。

2021-05-30 05:26 UTC, Shunsuke-Shimura reviewed
コメントしました。

2021-05-30 09:01 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +        self.client.login(username='username3', password='password_3')
消しました。

2021-05-30 09:02 UTC, shizuka12 commented on mysite/accounts/views.py
> +        following = User.objects.get(pk=user_id)
変更しました。

2021-05-30 09:02 UTC, shizuka12 commented on mysite/accounts/views.py
> +        following = User.objects.get(pk=user_id)
変更しました。

2021-05-30 09:02 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        request = reverse('accounts:unfollow', args=str(2))
変更しました。

2021-05-30 09:17 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        self.assertEqual(followings, 3)
この161~164行目を消去し、
`self.assertTrue(Follow.objects.filter(follower=self.user1, following=self.user3).exists())`
と書き換えました。

2021-05-30 09:18 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        Follow.objects.get_or_create(follower_id=1, following_id=3)
変更しました。

2021-05-30 09:19 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        Follow.objects.get_or_create(follower_id=3, following_id=1)
変更しました。

2021-05-30 09:19 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        request = reverse('accounts:follow', args=str(1))
変更しました。

2021-05-30 10:24 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        self.assertEqual(queryset.first(), None)
この135, 136行目を消して、
`self.assertFalse(Follow.objects.filter(follower=self.user1, following=self.user1).exists())`
に書き換えました。

2021-05-30 12:20 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        follower_id_list = [3, 2]
https://github.com/shizuka12/final-tasks/blob/b9ed8d694b66486fbca4a9698cc95af1a887e1e9/mysite/accounts/tests.py#L180-L186
idは使わず、データベースからフォロワーのユーザーネームを取り出して、それがfollower_detailに表示されることを確認する、というテストに変更しようとしました。
ですが、このように書くと、フォロワーのユーザーネームではなく、`<QuerySet [{'follower__username': 'username2'}, {'follower__username': 'username3'}]>`とクエリセット自体が取り出されてしまい、上手くいきませんでした。
そもそもクエリセットの中からフォロワーのユーザーネームを取り出す方法がよく分かりません。教えていただけないでしょうか？

2021-05-30 12:25 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        self.assertEqual(queryset[0].follower.username, "username1")
https://github.com/shizuka12/final-tasks/blob/b9ed8d694b66486fbca4a9698cc95af1a887e1e9/mysite/accounts/tests.py#L121-L127
ここでは、`Follow.objects.filter(follower=self.user1, following=self.user2).get()`というようにget()を使った方がいいのでしょうか？
この127行目のようにexists()を使った方法ではだめでしょうか？

2021-05-30 13:18 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        follower_id_list = [3, 2]
`values`なしの`QuerySet`で返るのはいわばモデルのインスタンスのリストなので、今回で言えば`Follow.objects.all()`とした後に、`for`文で繰り返して個々のインスタンスを取り出し、そのアトリビュートにアクセスすればいいです。
あと、`self.assertContains`の使い方も間違っています。

2021-05-30 13:19 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        self.assertEqual(queryset[0].follower.username, "username1")
いや、自分の勘違いでした。
それで大丈夫です。

2021-05-30 13:50 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        follower_id_list = [3, 2]
`self.assertContains`の使い方も間違っているとのことですが、どこが間違っているのか分かりませんでした。教えていただけないでしょうか？
<br>
また、
https://github.com/shizuka12/final-tasks/blob/bb288acf047771d4221bb4967bac705c21bda9e0/mysite/accounts/tests.py#L180-L187
このように`for`文を使ってフォロワーのユーザーネームを取り出すように修正したところ、テスト自体は成功したのですが、これも`self.assertContains`の使い方が間違っているのでしょうか？

2021-05-30 14:34 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        follower_id_list = [3, 2]
いや、最初はイテラブルオブジェクトを直接比較しようとしていたので指摘しました。

2021-05-30 14:36 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +from django.shortcuts import get_object_or_404
使っていないようなので消しましょう。

2021-05-30 14:37 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +from accounts.models import Follow
使っていないようなので消しましょう。

2021-05-30 14:38 UTC, Shunsuke-Shimura commented on mysite/accounts/views.py
> +        return redirect('tmitter:top')
ここは、`get_object_or_404`を使ったので例外処理はいりません。

2021-05-30 14:41 UTC, Shunsuke-Shimura commented on mysite/accounts/views.py
> +            unfollow = Follow.objects.get(follower=follower, following=following)
ここも`get_object_or_404`を使って例外処理を消してしまいましょう。

2021-05-30 14:44 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
>  from django.test import TestCase, Client
Clientも使っていないようなので消してしまいましょう。

2021-05-30 15:13 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        following_id_list = [3, 2]
上の`test_follower_list`と同じ要領で修正しました。
https://github.com/shizuka12/final-tasks/blob/bb288acf047771d4221bb4967bac705c21bda9e0/mysite/accounts/tests.py#L200-L209

2021-05-30 15:14 UTC, shizuka12 commented on mysite/accounts/tests.py
> +from django.shortcuts import get_object_or_404
`get_object_or_404`の`import`のコードを消しました。

2021-05-30 15:17 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +from accounts.models import Follow
`Follow`の`import`のコードを消しました。

2021-05-30 15:17 UTC, shizuka12 commented on mysite/accounts/views.py
> +        return redirect('tmitter:top')
例外処理の表記を消しました。

2021-05-30 15:17 UTC, shizuka12 commented on mysite/accounts/views.py
> +            unfollow = Follow.objects.get(follower=follower, following=following)
例外処理の表記を消しました。

2021-05-30 15:18 UTC, shizuka12 commented on mysite/tmitter/tests.py
>  from django.test import TestCase, Client
消しました。

2021-05-30 23:29 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        Follow.objects.create(follower_id=1, following_id=3)
ここもid表記になっていますので直しましょう。

2021-05-30 23:31 UTC, Shunsuke-Shimura commented on mysite/accounts/views.py
> +        unfollow = Follow.objects.get(follower=follower, following=following)
ここも`get_object_or_404`に変えましょう。

2021-05-30 23:32 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        Follow.objects.create(follower_id=1, following_id=3)
ここもid表記になっています。

2021-05-30 23:40 UTC, Shunsuke-Shimura reviewed
`accounts`と`tmitter`のテストでidをハードコードしている部分が多いので、そこを全部確認して修正するようにしてください。
テストの可読性の観点からもそのようにした方がいいと思います。
具体的には、`reverse`ショートカットなどで数字を直接記述しているところに対して、`user.pk`とするなどです。

2021-05-31 02:07 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        Follow.objects.create(follower_id=1, following_id=3)
直しました。

2021-05-31 02:08 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        Follow.objects.create(follower_id=1, following_id=3)
直しました。

2021-05-31 02:08 UTC, shizuka12 commented on mysite/accounts/views.py
> +        unfollow = Follow.objects.get(follower=follower, following=following)
変えました。

2021-05-31 02:11 UTC, shizuka12 commented
> `accounts`と`tmitter`のテストでidをハードコードしている部分が多いので、そこを全部確認して修正するようにしてください。
> テストの可読性の観点からもそのようにした方がいいと思います。
> 具体的には、`reverse`ショートカットなどで数字を直接記述しているところに対して、`user.pk`とするなどです。

他のテストでもidを使っていた箇所はすべて変更しました。
<br>
また、`test_by_another_user`の150,151行目が
https://github.com/shizuka12/final-tasks/blob/d24c4b720527ff9c21d104a297cd355c2467656c/mysite/tmitter/tests.py#L143-L151
のように`queryset`を使った形でテストをしていましたが、
https://github.com/shizuka12/final-tasks/blob/555dedce25581a3337245de6f86f549dbb8e0372/mysite/tmitter/tests.py#L141-L148
のように`Tmeet.objects.filter(author=self.user1).exists()`を使ってのテストに変更しました。

2021-05-31 02:33 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        request = reverse('accounts:follow', args=str(2))
ここもidのハードコードになっています。
欲を言えば
`reverse('accounts:follow', kwargs={'user_id': self.user2.pk}`
などとした方がより分かりやすいコードになります。

2021-05-31 02:33 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        url = reverse('accounts:follow', args=str(1))
ここもです

2021-05-31 02:34 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        request = reverse('accounts:follow', args=str(2))
他の`reverse`関数についても確認して修正お願いします。

2021-05-31 02:42 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +class Folllowing_detailViewTests(TestCase):
pep8の規約ではクラス名は基本的にキャメルケースが推奨されています。
参考
[https://pep8-ja.readthedocs.io/ja/latest/#id32](url)

2021-05-31 02:43 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +class Folllowing_detailViewTests(TestCase):
上のクラス名についても修正お願いします。

2021-05-31 03:59 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        request = reverse('accounts:follow', args=str(2))
`reverse`関数でハードコードになっていたところをすべて変更しました。

2021-05-31 03:59 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        url = reverse('accounts:follow', args=str(1))
変更しました。

2021-05-31 04:00 UTC, shizuka12 commented on mysite/accounts/tests.py
> +class Folllowing_detailViewTests(TestCase):
`Folllower_detailViewTests`、`Folllowing_detailViewTests`をそれぞれ`FolllowerDetailViewTests`、`FolllowingDetailViewTests`という名前に変更しました。

2021-05-31 04:09 UTC, Shunsuke-Shimura commented on mysite/accounts/tests.py
> +        request = reverse('accounts:follow', kwargs={'user_id': self.user2.pk})
これはurlを表すので、変数名はurlがいいでしょう。

2021-05-31 04:23 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        request = reverse('accounts:follow', kwargs={'user_id': self.user2.pk})
変更しました。

2021-05-31 04:24 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +            pk = t.pk
ここはなぜforを用いたのでしょうか

2021-05-31 04:31 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
>      def setUp(self):
すみません。前回見落としていたようなのですが、これは`DeleteView`のテストになっていません。
もう一度このクラス全体の処理の流れを追って見直してみてください。

デリートするツイートは一つで十分なはずです。
また、インスタンスに対する`delete()`メソッドは直接データベースから削除するものです。

2021-05-31 05:21 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +            pk = t.pk
`response = self.client.post(reverse('tmitter:delete_tmeet', args=str(1)))`
で、argsのところがハードコードになっていたので、ツミートのpkを取得して、pk変数に入れたのち、
`response = self.client.post(reverse('tmitter:delete_tmeet', args=str(pk)))`
として、ハードコードを回避しようとしました。

そこで、まずpkを取得するために、
`pk =Tmeet.objects.filter(content='This is a deleteing funtction test1 by username1').pk `
というコードを書いたのですが、
`AttributeError: 'QuerySet' object has no attribute 'pk'` 
とエラーになってしまいました。

なので、クエリセットから中身を取り出すためにfor文を使いました。

2021-05-31 05:36 UTC, shizuka12 commented on mysite/tmitter/tests.py
>      def setUp(self):
テストをこのように修正したのですが、これで大丈夫でしょうか？
https://github.com/shizuka12/final-tasks/blob/67fb0f0e20201a9109f80bcab910f493a0f4974c/mysite/tmitter/tests.py#L82-L98

2021-05-31 11:27 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +            pk = t.pk
for文の目的は反復処理を簡単化することなので、一つしかオブジェクトがないことがわかっている場合は
`filter().get()`でいいと思います。

2021-05-31 11:31 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> -        self.deltest_list.reverse()
ツイートのデリートのテストのみであればこのfor文はいらないと思います。

2021-05-31 11:32 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
>      def setUp(self):
はい、テストの流れとしてはそれで大丈夫だと思います。
あとはfor文を消去すればいいでしょう。

2021-05-31 12:02 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +            pk = t.pk
`filter().get()`を使ったコードに修正していましたが、このように
https://github.com/shizuka12/final-tasks/blob/4a78ff421dd616c3a861294f6d7ce91fd39a20e4/mysite/tmitter/tests.py#L83-L87
`setUp`の時点で、`self.t =Tmeet.objects.create(author=self.user1, content=content)`と置いてから、`self.t.pk`でpkを取得する方がすっきりとしたコードになると気づいたので、このように書き方を改めました。

2021-05-31 12:03 UTC, shizuka12 commented on mysite/tmitter/tests.py
>      def setUp(self):
for文を消去しました。

2021-05-31 12:03 UTC, shizuka12 commented on mysite/tmitter/tests.py
> -        self.deltest_list.reverse()
消しました。

2021-05-31 13:08 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +            pk = t.pk
いいですね！

2021-05-31 13:09 UTC, Shunsuke-Shimura commented on mysite/tmitter/tests.py
> +            pk = t.pk
ただ、さすがに`t`だけだと短すぎるので、`tmeet`にしましょう。

2021-05-31 13:15 UTC, shizuka12 commented on mysite/tmitter/tests.py
> +            pk = t.pk
変更しました。

2021-06-01 12:00 UTC, Akinori13 requested changes
Unfollowのテストに修正すべき点があります。

2021-06-01 12:00 UTC, Akinori13 commented on mysite/tmitter/views.py
> +        'already_followed': Follow.objects.filter(follower__username=request.user.username).filter(following__username=user.username),
```suggestion
        'is_following': Follow.objects.filter(follower__username=request.user.username, following__username=user.username).exists(),

```

2021-06-01 12:00 UTC, Akinori13 commented on mysite/tmitter/views.py
> +        'follower_num': Follow.objects.filter(following__username=user.username).count(),
[参考]
Modelで`related_name`を設定しているので、↓みたいな書き方もできます。
```python3
'following_num': user.follower.count(),
'follower_num': user.following.count(),
```

2021-06-01 12:00 UTC, Akinori13 commented on mysite/accounts/tests.py
> +        self.assertTrue(Follow.objects.filter(follower=self.user1, following=self.user3).exists())
`user1`の`user2`へのフォローを削除するので、確かめるのは`user1`による`user2`に対するフォローでは？

2021-06-01 12:24 UTC, shizuka12 commented on mysite/tmitter/views.py
> +        'follower_num': Follow.objects.filter(following__username=user.username).count(),
そちらの書き方に変更しました。

2021-06-01 12:25 UTC, shizuka12 commented on mysite/accounts/tests.py
> +        self.assertTrue(Follow.objects.filter(follower=self.user1, following=self.user3).exists())
そうでした。
159行目を
`self.assertFalse(Follow.objects.filter(follower=self.user1, following=self.user2).exists())`
に書き換えました。

2021-06-01 13:45 UTC, Akinori13 approved these changes

2021-06-01 13:46 UTC, Akinori13 commented
LGTM!
次のいいね機能では、Ajax(jQueryのAjax, Vue.jsのAxios, xhr, Fetch)を使ってみてください。

2021-06-01 13:46 UTC, merged